services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mariadb:3306/cleanfastapi
    depends_on:
      - mariadb
    volumes:
      - ./src:/app/src
      - .:/app # Monta todo el directorio raíz del proyecto
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=cleanfastapi
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "5306:3306"

volumes:
  mariadb_data:
